Tensor

In [5]:
from __future__ import print_function
import torch as t
t.__version__

'1.13.0'

In [6]:
# 构建5 x 3矩阵, 只分配了空间, 没有初始化
x = t.Tensor(5, 3)
x

tensor([[1.0286e-38, 1.0653e-38, 1.0194e-38],
        [8.4490e-39, 1.0469e-38, 9.3674e-39],
        [9.9184e-39, 8.7245e-39, 9.2755e-39],
        [8.9082e-39, 9.9184e-39, 8.4490e-39],
        [9.6429e-39, 1.0653e-38, 1.0469e-38]])

In [7]:
#使用0 1 巨晕分布随即初始化二维数组
x = t.rand(5, 3)
x

tensor([[0.5487, 0.8616, 0.0539],
        [0.2441, 0.2400, 0.5364],
        [0.4074, 0.9052, 0.7939],
        [0.7068, 0.8362, 0.0728],
        [0.9282, 0.0246, 0.6805]])

In [8]:
print(x.size()) #产看x的形状
x.size()[1], x.size(1) #查看列数, 两个方法都可

torch.Size([5, 3])


(3, 3)

In [9]:
y = t.rand(5, 3)

In [10]:
x + y

tensor([[0.6921, 1.7878, 0.4833],
        [0.3823, 0.8640, 0.7689],
        [0.7413, 1.6653, 1.6233],
        [0.7080, 1.5850, 0.2982],
        [1.7833, 0.7285, 1.2901]])

In [11]:
t.add(x, y)

tensor([[0.6921, 1.7878, 0.4833],
        [0.3823, 0.8640, 0.7689],
        [0.7413, 1.6653, 1.6233],
        [0.7080, 1.5850, 0.2982],
        [1.7833, 0.7285, 1.2901]])

In [12]:
result = t.Tensor(5, 3)
t.add(x, y, out=result)
result

tensor([[0.6921, 1.7878, 0.4833],
        [0.3823, 0.8640, 0.7689],
        [0.7413, 1.6653, 1.6233],
        [0.7080, 1.5850, 0.2982],
        [1.7833, 0.7285, 1.2901]])

In [13]:
print("origin y")
print(y)

print('unchange y value')
y.add(x)
print(y)

print('change y value')
y.add_(x)
print(y)

origin y
tensor([[0.1434, 0.9262, 0.4295],
        [0.1381, 0.6240, 0.2325],
        [0.3339, 0.7600, 0.8294],
        [0.0012, 0.7488, 0.2254],
        [0.8550, 0.7040, 0.6096]])
unchange y value
tensor([[0.1434, 0.9262, 0.4295],
        [0.1381, 0.6240, 0.2325],
        [0.3339, 0.7600, 0.8294],
        [0.0012, 0.7488, 0.2254],
        [0.8550, 0.7040, 0.6096]])
change y value
tensor([[0.6921, 1.7878, 0.4833],
        [0.3823, 0.8640, 0.7689],
        [0.7413, 1.6653, 1.6233],
        [0.7080, 1.5850, 0.2982],
        [1.7833, 0.7285, 1.2901]])


In [14]:
y[:, 0] # 支持切片操作, tensor 涵盖了 numpy的方法

tensor([0.6921, 0.3823, 0.7413, 0.7080, 1.7833])

In [15]:
a = t.ones(5) #生成全是1 的向量
a

tensor([1., 1., 1., 1., 1.])

In [16]:
import numpy as np
b = a.numpy() # tensor -> numpy
print(b)
print(type(b))

[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>


In [17]:
a = np.ones(6)
b = t.from_numpy(a) #numpy -> tensor
print(a)
print(b)


[1. 1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1., 1.], dtype=torch.float64)


#### 转换前后的 tensor 和 numpy共享内存， 转换速度快， 几乎不消耗其他资源， 但是任何操作都会同时导致两个
#### 对象的改变

In [18]:
b.add(1)
print(a)
print(b)


[1. 1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1., 1.], dtype=torch.float64)


In [19]:
b.add_(1)
print(a)
print(b)

[2. 2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2., 2.], dtype=torch.float64)


In [20]:
c = b;
b.add_(2)
print(a)
print(b)
print(c)

[4. 4. 4. 4. 4. 4.]
tensor([4., 4., 4., 4., 4., 4.], dtype=torch.float64)
tensor([4., 4., 4., 4., 4., 4.], dtype=torch.float64)


##### 可见a, b, c共享内存
##### 若只想获取一个值 可以使用scalar.item

In [21]:
d = a[1]
d = 10
print(a)
print(b)
print(c)
print(d)

[4. 4. 4. 4. 4. 4.]
tensor([4., 4., 4., 4., 4., 4.], dtype=torch.float64)
tensor([4., 4., 4., 4., 4., 4.], dtype=torch.float64)
10


In [22]:
scalar = b[0]
scalar

tensor(4., dtype=torch.float64)

In [23]:
scalar.size()

torch.Size([])

In [24]:
scalar.item()

4.0

In [25]:
tensor = t.tensor([2])

In [26]:
tensor, scalar

(tensor([2]), tensor(4., dtype=torch.float64))

In [27]:
#只有一个元素的tensor也可以调用item()方法
t1 = t.tensor([1, 2])
t2 = t.tensor([3])

In [28]:
t1.item()

ValueError: only one element tensors can be converted to Python scalars

In [ ]:
t2.item()

In [ ]:
old_tensor = t.tensor([1,2,3])
new_tensor = old_tensor.clone()
new_tensor[0] = 11111
old_tensor, new_tensor

#### t.tensor() 和 tensor.clone() 总是会进行数据拷贝, 新旧tensor不共享内存
#### 如果要共享内存可以使用 tensor.from_numpy() 或者 tensor.detach()来新建一个tensor
#### 二者共享内存

In [ ]:
new_tensor2 = old_tensor.detach()
new_tensor2[2] = 3333
old_tensor, new_tensor, new_tensor2

#### tensor可以通过 .cuda方法转为GPU的tensor，从而享受GPU带来的加速运算

## autograd：自动微分

##### 深度学习的算法本质是通过反向传播求倒数，而pytorch的autograd模块则实现了这个功能
##### tensor上的所有操作 autograd都能自动的计算 微分
##### 从0.4起Variable正式并入Tensor，说明Tensor也能进行自动机打算微分的操作
##### 使用Tensor的autograd功能， tensor.requries_grad=True

In [ ]:
x = t.tensor([1.,2.,3.], requires_grad=True)
x

In [ ]:
y = (x + 1) ** 2
y

In [ ]:
y.grad_fn

In [ ]:
y.backward() #标量才能进行反向传播，修改如下

In [ ]:
y.backward(t.tensor([1,1,1]), retain_graph=True) #正确的
x.grad

<https://zhuanlan.zhihu.com/p/168748668>

##### 上面的例子 给出了x的三个值 1 2 3
##### y = (x + 1) ** 2
##### y 关于 x 的 导数 y' = 2 ( x + 1 )
##### 所以最后输出 4 6 8
##### 我的理解 先定义 自变量 在定义函数 在进行backward 就是求导
##### 反向传播是神经网络最核心的部分。 反向传播，可以看成链式求导过程，一环套一环，通过对误差最终的损失函数求导，损失函数对每个参数进行求导，求导过程就是反向传播过程

In [ ]:
y.backward(t.tensor([1,1,1])) #正确的
x.grad

In [ ]:
y.backward(t.tensor([1,1,1])) #正确的
x.grad

##### 报错原因就是pytorch的计算图在第一次执行完backward计算梯度的时候就已经被释放了。第二次想要再用计算图计算时，计算图已经没了，自然报错。
##### 解决方法之一就是 在 backward()里面加上retain_graph=True
##### 但是会导致内存消耗

# 神经网络

In [30]:
import torch.nn as nn
import torch.nn.functional as F

#https://blog.csdn.net/qq_42079689/article/details/102642610

class Net(nn.Module):
    def __init__(self):
        # nn.Module子类的函数必须在构造函数中执行弗雷德构造函数
        # 下面句子等价 nn.Module.__init__(self)
        super(Net, self).__init__()

        #卷积层 ‘1’表示输入图片为单通道, '6'表示输出通道的数目, '5'表示卷积核为5*5
        self.conv1 = nn.Conv2d(1, 6, 5)
        #卷积层
        self.conv2 = nn.Conv2d(6, 16, 5)
        #全链接层(仿射层), y = Wx +　ｂ
        self.fc1 = nn.Linear(16*5*5, 120)
        #16 * 5 * 5是经过了两个卷积层后得到的 作为全链接层的输入
        self.fc2 = nn.Linear(120, 84)
        self.fc3 = nn.Linear(84, 10)

    def forward(self, x):
        #卷积 -> 激活 -> 池化
        x = F.max_pool2d(F.relu(self.conv1(x)), (2, 2))
        x = F.max_pool2d(F.relu(self.conv2(x)), 2)
        x = x.view(x.size()[0], -1) #size() 查看 维度
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)

        return x


net = Net()
print(net)



Net(
  (conv1): Conv2d(1, 6, kernel_size=(5, 5), stride=(1, 1))
  (conv2): Conv2d(6, 16, kernel_size=(5, 5), stride=(1, 1))
  (fc1): Linear(in_features=400, out_features=120, bias=True)
  (fc2): Linear(in_features=120, out_features=84, bias=True)
  (fc3): Linear(in_features=84, out_features=10, bias=True)
)


##### 只要在nn.Module的子类中定义了forward函数，backward函数就会自动被实现(利用autograd)。在forward 函数中可使用任何tensor支持的函数，还可以使用if、for
##### 循环 print、log等Python语法，写法和标准的Python写法一致。

In [31]:
params = list(net.parameters())
print(len((params)))

10


In [32]:
for name, parameters in net.named_parameters():
    print(name, ':', parameters.size())

conv1.weight : torch.Size([6, 1, 5, 5])
conv1.bias : torch.Size([6])
conv2.weight : torch.Size([16, 6, 5, 5])
conv2.bias : torch.Size([16])
fc1.weight : torch.Size([120, 400])
fc1.bias : torch.Size([120])
fc2.weight : torch.Size([84, 120])
fc2.bias : torch.Size([84])
fc3.weight : torch.Size([10, 84])
fc3.bias : torch.Size([10])


In [33]:
input = t.randn(1, 1, 32, 32)
out = net(input)
out.size()
out.size()[1]

10

In [34]:
net.zero_grad()
out.backward(t.ones(1, out.size()[1]))

##### batch批， 采用批处理， 能够 提升内存利用率 减少迭代次数， torch.nn只支持mini-batches,
##### 不支持一次只输入 一个样本， 即 一次必须是一个batch， 但是如果只想输入一个样本， 那么用input.unsqueeze(0)
##### 把batch_size设置为1， 比如 nn.Conv2d 的输入必须是4维的，
##### 形如 nSample x nChannels x Height x Width, 可以将nSample
##### 设置为1， 即 1 x nChannels x Height x Width

### 损失函数
##### nn实现了神经网络中的大多数的损失函数， 例如nn.MSELoss用来计算均方误差
##### nn.CrossEntropyLoss来计算交叉熵损失

In [35]:
output = net(input)
target = t.arange(0,10).view(1,10).float()
criterion = nn.MSELoss()
loss = criterion(output, target)
loss

tensor(28.3272, grad_fn=<MseLossBackward0>)

##### 如果对loss进行反向传播溯源(使用gradfn属性)，可以看到他的计算过程如下
##### input -> conv2d -> relu -> maxpool2d -> conv2d -> relu -> maxpool2d
##### view -> linear -> relu -> linear -> relu -> linear
##### MSELoss
##### loss