### 3.1 Tensor

In [2]:
from __future__ import print_function
import torch as t
t.__version__

'1.13.1'

###### 从接口的角度来讲, 对tensor的操作分为两类
> torch.function   如 torch.save等
> 另一类是 tensor.function 如 tensor.view
###### 一般来说 tensor的大部分操作同时支持这两类接口 如torch.sum (torch.sum(a, b))与tensor.sum (a.sum(b))功能等价
###### 从存储的角度来说, 对tensor的操作可分为两类
> 不会修改自身的数据 如 a.add(b) 加法的结果会返回一个新的tensor
>   会修改自身的数据 如 a.add_(b) 假发的结果在 a中 a被修改
函数名用 _ 位结尾都是 inplace 方式 就是会修改自身的数据 要注意

|     函数     | 功能 |
|:----------:|:--:|
| eye(*size) | 对角线为1, 其他是0 |
|arange(s, e, step)|从s到e步长为step|
|linspace(s, e, step)|从s到e， 均匀分成step份|
|rand/randn(*size)|均匀/标准分布|
|normal(mean, std)/uniform(from, to)|正态分布/均匀分布|
|randperm(m)|随机排列|

###### Tensor 能够接收一个 list 并根据list来创建tensor, 也能根据指定的形状创建tensor
###### 还能传入其他的tensor

In [3]:
#指定tensor形状
a = t.Tensor(5, 3)
a #数值取决于内存空间的状态 print的时候可能内存溢出(overflow)

tensor([[9.3582e+25, 5.2268e-43, 9.3582e+25],
        [5.2268e-43, 9.3582e+25, 5.2268e-43],
        [9.3582e+25, 5.2268e-43, 9.3582e+25],
        [5.2268e-43, 9.3582e+25, 5.2268e-43],
        [9.3582e+25, 5.2268e-43, 9.3582e+25]])

In [4]:
#用list来创建tensor
b = t.Tensor([[2, 3, 1], [6, 4, 5]])
b

tensor([[2., 3., 1.],
        [6., 4., 5.]])

In [5]:
cc = b.tolist()
b, cc

(tensor([[2., 3., 1.],
         [6., 4., 5.]]),
 [[2.0, 3.0, 1.0], [6.0, 4.0, 5.0]])

In [6]:
b_size = b.size()
b_size

torch.Size([2, 3])

In [7]:
b.numel()#b中元素个数

6

In [8]:
#创建一个和b形状一致的tensor
c = t.Tensor(b_size)
d = t.Tensor((2, 3))
c, d

(tensor([[1.4586e-19, 1.1578e+27, 2.0780e-07],
         [6.0542e+22, 7.8675e+34, 4.6894e+27]]),
 tensor([2., 3.]))

###### tensor.shape 等价于 tensor.size()

In [9]:
c.shape

torch.Size([2, 3])

###### t.Tensor在创建tensor时, 系统不会马上分配空间, 只是计算剩余的内存是否足够使用
###### 使用的时候才分配, 其他方法都是创建王就立刻分配

In [10]:
t.ones(3, 2)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [11]:
t.zeros(2, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [12]:
t.arange(3, 8, 3)

tensor([3, 6])

In [13]:
t.linspace(2, 9, 4)

tensor([2.0000, 4.3333, 6.6667, 9.0000])

In [14]:
t.randn(2, 3, device=t.device('cpu'))

tensor([[-0.0137, -3.1169,  0.4358],
        [ 0.0688, -0.9607, -1.1864]])

In [15]:
t.randperm(6) #长度是6的随机排列

tensor([1, 3, 5, 0, 2, 4])

In [16]:
t.eye(2, 3, dtype=int)

tensor([[1, 0, 0],
        [0, 1, 0]])

In [17]:
scalar = t.tensor(3.14159)
print('scalar : %s, shape of scalar : %s' %(scalar, scalar.size()))
scalar.shape

scalar : tensor(3.1416), shape of scalar : torch.Size([])


torch.Size([])

In [18]:
vec = t.tensor([2, 3, 4])
print('vec : %s, shape of vec : %s' %(vec, vec.shape))

vec : tensor([2, 3, 4]), shape of vec : torch.Size([3])


In [19]:
vec2 = t.Tensor([2, 3, 4])
print('vec2 : %s, shape of vec2 : %s' %(vec2, vec2.shape))

vec2 : tensor([2., 3., 4.]), shape of vec2 : torch.Size([3])


In [20]:
vec3 = t.tensor(2, 3, 4)
print('vec3 : %s, shape of vec3 : %s' %(vec3, vec3.shape))

TypeError: tensor() takes 1 positional argument but 3 were given

In [ ]:
vec4 = t.Tensor(2, 3, 4)
print('vec4 : %s, shape of vec4 : %s' %(vec4, vec4.shape))

In [ ]:
matrix = t.tensor([[0.1, 1.2], [2.4, 3.7], [6., 7.7]])
matrix, matrix.shape

In [ ]:
tt = t.tensor([[0.11111, 0.222222, 0.3333333]],
                     dtype=t.float64,
                     device=t.device('cpu'))
tt, tt.shape

In [ ]:
empty_tensor = t.tensor([])
empty_tensor.shape

### 常用Tensor操作

###### 通过tensor.view 可以调整tensor的形状, 但是必须保持调整前后的元素总数一直。view不会
###### 修改自身的数据, 返回的新的tensor和原tensor共享内存, 改变其中一个另一个也会发生改变
###### 实际应用中可能经常需要添加或者减少某一维度, 这就要用到squeeze 和 unsqueeze

In [ ]:
a = t.arange(1, 9) #不包含9 即 [1, 9)左闭右开
a.view(4, 2)

In [21]:
b = a.view(2, -1) #有-1的时候会自动计算维度
b, b.shape

RuntimeError: shape '[2, -1]' is invalid for input of size 15

In [ ]:
us1 = b.unsqueeze(1)
us1, us1.shape

In [ ]:
us2 = b.unsqueeze(0)
us2, us2.shape

In [ ]:
us3 = b.unsqueeze(2)
us3, us3.shape

##### unsqueeze(idx) 在第几维增加一维
##### squeeze(idx) 在第几维减少一维

In [22]:
st = t.arange(0, 8)
sa = st.view(1, 1, 1, 2, 4)
sb = sa.squeeze(0)
sa, sb

(tensor([[[[[0, 1, 2, 3],
            [4, 5, 6, 7]]]]]),
 tensor([[[[0, 1, 2, 3],
           [4, 5, 6, 7]]]]))

In [23]:
sst = t.Tensor([[1, 2, 3, 4], [1, 2, 3, 4]])
ssa = sst.view(4, 2)
ssb = t.squeeze(ssa, 0)
ssa, ssa.shape, ssb, ssb.shape

(tensor([[1., 2.],
         [3., 4.],
         [1., 2.],
         [3., 4.]]),
 torch.Size([4, 2]),
 tensor([[1., 2.],
         [3., 4.],
         [1., 2.],
         [3., 4.]]),
 torch.Size([4, 2]))

In [24]:
sst[0][0] = 100

In [25]:
ssa, ssb

(tensor([[100.,   2.],
         [  3.,   4.],
         [  1.,   2.],
         [  3.,   4.]]),
 tensor([[100.,   2.],
         [  3.,   4.],
         [  1.,   2.],
         [  3.,   4.]]))

###### resize 也可以重新分配大小，不过区别于view，当元素数目不满足分为新的唯独所需要的数目
###### 会报错， 而 resize 不会， 当新的维度的元素数目少于 原来的维度元素数目 就会
###### 截取一部分 而当新的维度的元素数目大于 原来的维度元素数目 就会分配额外空间

In [26]:
ttt = t.arange(0, 8)
ttt

tensor([0, 1, 2, 3, 4, 5, 6, 7])

In [27]:
ttta = ttt.view([2, 4])
ttta

tensor([[0, 1, 2, 3],
        [4, 5, 6, 7]])

In [28]:
tttc = ttta.resize(4, 2)
tttc

C:\Users\liuhao\.conda\envs\PyTorch\lib\site-packages\torch\_tensor.py:761: UserWarning: non-inplace resize is deprecated
  warnings.warn("non-inplace resize is deprecated")


tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7]])

In [29]:
tttd = ttta.resize(3, 3)
tttd

RuntimeError: requested resize to 3x3 (9 elements in total), but the given tensor has a size of 2x4 (8 elements). autograd's resize can only change the shape of a given tensor, while preserving the number of elements. 

###### 看来resize和view没什么区别 resize不能填充或者删除元素

In [30]:
ttta.resize_(3, 3)

tensor([[                  0,                   1,                   2],
        [                  3,                   4,                   5],
        [                  6,                   7, 7308535291872879145]])

In [31]:
ttta.resize_(1, 2)

tensor([[0, 1]])

#### resize_ 行！！！

#### 索引操作
###### 类似numpy.ndarray

In [34]:
a = t.randn(3, 4)
a

tensor([[-1.0166, -0.9107, -0.4300,  0.4374],
        [-0.6738,  0.6675,  1.4845, -0.6912],
        [ 1.5548,  0.3883,  0.7748, -0.8407]])

In [36]:
b = a[0]
a[0] = 100
a, b #a b共享内存

(tensor([[100.0000, 100.0000, 100.0000, 100.0000],
         [ -0.6738,   0.6675,   1.4845,  -0.6912],
         [  1.5548,   0.3883,   0.7748,  -0.8407]]),
 tensor([100., 100., 100., 100.]))

In [38]:
c = a[None]
c, c.shape#None 相当于 view(1, a.shape[0], a.shape[1])

(tensor([[[100.0000, 100.0000, 100.0000, 100.0000],
          [ -0.6738,   0.6675,   1.4845,  -0.6912],
          [  1.5548,   0.3883,   0.7748,  -0.8407]]]),
 torch.Size([1, 3, 4]))

In [39]:
d = a[:, None, :]
e = a[:, None, :, None, None]
d.shape, e.shape

(torch.Size([3, 1, 4]), torch.Size([3, 1, 4, 1, 1]))

In [40]:
a > 1

tensor([[ True,  True,  True,  True],
        [False, False,  True, False],
        [ True, False, False, False]])

In [43]:
f = a[a > 1]
f[1] = 0
f, a
#选择结果 不共享内存 相当于 masked_select(a > 1)

(tensor([100.0000,   0.0000, 100.0000, 100.0000,   1.4845,   1.5548]),
 tensor([[100.0000, 100.0000, 100.0000, 100.0000],
         [ -0.6738,   0.6675,   1.4845,  -0.6912],
         [  1.5548,   0.3883,   0.7748,  -0.8407]]))

In [45]:
a = t.arange(1, 17).view(4, 4)
a

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]])

In [48]:
index = t.LongTensor([[3, 2, 1, 0]])
#(0, 0) (0, 1) (0, 2) (0, 3)
#dim = 0, 1
#dim = 0 就是用index替换坐标的第一位
#比如 (3, 0) (2, 1) (1, 2) (0, 3)
#答案是 13, 10, 7, 4
b = a.gather(0, index)
b

tensor([[13, 10,  7,  4]])

In [49]:
b.shape

torch.Size([1, 4])

In [51]:
b[0][2] = -1
a, b #不共享内存

(tensor([[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12],
         [13, 14, 15, 16]]),
 tensor([[13, 10, -1,  4]]))

In [52]:
index = t.LongTensor([[0, 1, 2, 3], [3, 2, 1, 0]]).t()
index

tensor([[0, 3],
        [1, 2],
        [2, 1],
        [3, 0]])

In [63]:
b = a.gather(0, index)
b

tensor([[ 1, 14],
        [ 5, 10],
        [ 9,  6],
        [13,  2]])

In [64]:
c = t.zeros(16).view(4, 4)
c

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [66]:
c.scatter_(1, index, b.float())
c

tensor([[ 1.,  2.,  0., 14.],
        [ 5.,  5., 10.,  0.],
        [ 9.,  6.,  9.,  0.],
        [ 2., 14.,  0., 13.]])